# Generated by Django 5.0 on 2023-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_at', models.DateField(db_index=True, unique=True)),
                ('brl', models.FloatField()),
                ('eur', models.FloatField()),
                ('jpy', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
